url: "https://low-tech.the-green-emporium.com/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "The Low Tech Emporium" # the name of your site, e.g. ACME Corp.

jekyll_admin:
  hidden_links:
    - staticfiles
